// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnxkknyghjfaetynbyaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJueGtrbnlnaGpmYWV0eW5ieWF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMjgwOTUsImV4cCI6MjA1NzcwNDA5NX0.6-3UnEMsC5wlkSHmsMuZ8DbXQ31wLhQMvX1Q4UbcH4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);